### ISSUE TITLE
Primary Origin keys order

### ISSUE THREAD

**Issue by Lichtenshtein** [regorxxx/Search-by-Distance-SMP#17]
Hi. Сould you please explain the order of writing in the style_primary_origin section in the file music_graph_descriptors_xxx.js? The description says: 

	// Primary influence. For example one style being the origin of other.
	// For ex. 'Rockabilly' and 'Rockabilly revival'.
	
That means the origin to the left and the influenced sub-genres to the right, right?
Or the primary genres that influenced the genre at the left are the right?
I don't understand some of the entries like this one:

		['Nu-Disco'							,	['Electro','Disco XL','Post-Disco XL']],

This confuses me, because Nu-Disco is a sub-genre from the 21st century.

**Comment by regorxxx** [comment]
It doesn't really matter at all, since the link is bi-directional :)

I mean, you can stick to an specific convention for your own usage, but at the graph, it's just a 'primary influence' and it doesn't care at all about which one "appeared first" or any order. 

Also it needs to be bi-directional so you get the influence on both sides when calculating their 'distance'.

To add the date variable, there are currently other ways (like queries, date tag comparison, etc.).

**Comment by regorxxx** [comment]
Planned at some point:
- A dynamic query -at pre-scoring stage- to do things like: '%DATE% GREATER #CURRENTDATE#'; so you can force tracks with a date greater or lower than the current one (since it's configurable, you could set it to be a decade for ex). You can currently do this, but manually. [universally applicable]
- A date map. A cultural map was added some releases ago, assigning genres to cultural regions. I plan to do the same by date, so at that point even if the link is bidirectional there will be another set of data telling X appeared before Y, thus X being the origin of Y.  Then a filter to output only earlier/later genres would be trivial. [specific for dates]

**Comment by regorxxx** [comment]
> A dynamic query -at pre-scoring stage- to do things like: '%DATE% GREATER #CURRENTDATE#'; so you can force tracks with a date greater or lower than the current one (since it's configurable, you could set it to be a decade for ex). You can currently do this, but manually. [universally applicable]

This is now implemented here: https://github.com/regorxxx/Search-by-Distance-SMP/commit/1502bbc3d6b04aea8b327e543ac9ab659e083d98
