### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by regorxxx** [regorxxx/Search-by-Distance-SMP#26]
**Describe the bug**
Reference track's score not being 100 when using genre/style tags not present on the Graph.

**To Reproduce**
Enable or disable "Set search method\Filter values not present in the graph" for tracks with genres not being on the graph.

**Expected behavior**
Score of 100.

**Additional context**
[See this](https://github.com/regorxxx/Search-by-Distance-SMP/issues/25#issuecomment-1924711784)

**Comment by regorxxx** [comment]
@username116

**Comment by regorxxx** [comment]
Now fixed, I was only applying the filter on the analyzed tracks but not on the reference track, as result, the output tracks had sometimes less genre values then the reference track and thus less score. Now the filter is applied to both.

**Comment by username116** [comment]
I confirm that if I disable `Filter values not present on the graph`, the "Mantra" reference track gives a score of 100 instead of 83.3. And the playlist is larger.

Then I tried the new version, in a new panel with a new cache calculation. This time, the reference track gives a score of 100 in both cases, whether the filter is enabled or not. The playlists are the same, there are just a few tracks with the same score in a different order.

That's great. I'm glad to see this tool improving. Thank you.
